config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  resources :allproducts
  resources :electricals
  resources :readymades
  resources :groceries
  resources :products
  devise_for :supers
  devise_for :admins
  devise_for :users
  resources :users
  get 'welcome/index'
  get 'allproduct/rice'
  get 'welcome/productprice'
  get 'welcome/groceries'
  get 'welcome/electrical'
  get 'welcome/readymade'

   root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
     
end

app/models/allproduct.rb
class Allproduct < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

def self.search(search)
	puts "search"
  if search
  	puts "ifsearch"

    where('productname LIKE ?', "%#{search}%")
    puts "tttt"
  else
    @product = Product.all
  end
end


end

app/models/electrical.rb
class Electrical < ActiveRecord::Base
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Electrical.all
  end
end



end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Grocery.all
  end
end



end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Product.all
  end
end


# def search(search)
#   if search
#     find(:all, :conditions => ['productname LIKE ?', "%#{search}%"])
#   else
#     find(:all)
#   end
# end


  
end

app/models/readymade.rb
class Readymade < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Readymade.all
  end
end




end

app/models/role.rb
class Role < ActiveRecord::Base
	has_one:user
end

app/models/super.rb
class Super < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        belongs_to :role
      

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    puts "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
  	@product = Allproduct.search(params[:search])
    puts "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
  	#@product = Electrical.search(params[:search])
  	#@product = Grocery.search(params[:search])
  	#@product = Readymade.search(params[:search])
  	
  end
  def productprice
  end
  def groceries
  end
end

app/helpers/allproduct_helper.rb
module AllproductHelper
end

app/helpers/allproducts_helper.rb
module AllproductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/electricals_helper.rb
module ElectricalsHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/readymades_helper.rb
module ReadymadesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/welcome/_products.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%#= will_paginate @products %>

app/views/welcome/groceries.html.erb
<% @product = Grocery.all %>

    <div class="container">
      <div class="row" style="color:blue">
        
				<% @product.each do |f| %>
				<div class="col-lg-4">
					<% if f.productid == 2 %>
					<div class="img-thumbnail" >
								<%= image_tag (f.avatar.url(:thumb) )%></br>
								<% price = 1000 %>

					     <span> ProductPrice :<%= price %></span>
					       <p>CashBack :10%<p>
					       		<% cost=price/100 %>
					       		<% dis=cost*10 %>
					       		<% @selling =price-dis %>

					       	<span>cost:<%= @selling  %>
					       		
					       		<%= link_to "AddCard", "" %>
					</div>       	
					     <% end %>
				</div>
				<div class="col-lg-4">
					     <% if f.productid == 4 %>
					     <div class="img-thumbnail" >
								<%= image_tag (f.avatar.url(:thumb) )%></br>
								<% price = 1000 %>

					     <span> ProductPrice :<%= price %></span>
					       <p>CashBack :20%<p>
					       		<% cost=price/100 %>
					       		<% dis=cost*20 %>
					       		<% selling =price-dis %>

					       	<span>cost:<%= selling  %>
					       		<%= link_to "AddCard", "" %>
					      </div>
					     <% end %>







					    




	      		</div>
	      		<div class="col-lg-4" >
					     <% if f.productid == -3 %>
					     <div class="img-thumbnail" >
								<%= image_tag (f.avatar.url(:thumb) )%></br>
								<% price = 1000 %>

					     <span> ProductPrice :<%= price %></span>
					       <p>CashBack :40%<p>
					       		<% cost=price/100 %>
					       		<% dis=cost*40 %>
					       		<% selling =price-dis %>

					       	<span>cost:<%= selling  %>
					       		<%= link_to "AddCard", "" %>
					      </div>
					     <% end %>
					      
				</div>
				<% end %>







	   </div>
	</div>

app/views/welcome/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1 align="center"><%#=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
<div class="nav navbar-nav navbar-right">
<%= form_tag  welcome_index_path, :method => 'get', :id => "products_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="products"><%= render 'products' %></div>
<% end %>
</div>


<span>ALLPRODUCTS</span>
        

  </h1>
</div>
<div class="rowmainbg" style="color:#BD3F3F">

           <div class="container">
      <div class="row">
        <div class="col-lg-2">
          <% @product = Product.all %>
          <span>RICEproducts</span>
                    <% @product.each do |product| %>
                        <ul class="items">
                              <div class="img-thumbnail" >
                
              <%= image_tag (product.avatar.url(:thumb) )%></br>
              <span>products</span>
                              
              <li><span>productsid:</span><%= product.productid %></li>
              <li><span>productsname:</span><%= product.productname %></li>
              <li><span>productsdis:</span><%= product.productdiscription %></li>
              <%= link_to "ShopNow", welcome_productprice_path  %>




            </div>
            </ul>
            <% end %>
          </div>



          <%@grocery =Grocery.all  %>



          <div class="col-lg-2" >
            <span align="center">GROCERY</span>
                    <% @grocery.each do |grocery| %>
                        <ul class="items">
                              <div class="img-thumbnail">
                
              <%= image_tag grocery.avatar.url(:thumb) %></br>
              <span>groceries</span>
                              
              <li><span>productsid:</span><%= grocery.productid %></li>
              <li><span>productsname:</span><%= grocery.productname %></li>
              <li><span>productsdis:</span><%= grocery.productdiscription %></li>
              <%= link_to "ShopNow", welcome_groceries_path  %>
              </div>
            </ul>
            <% end %>
          </div>


          <%@readymade =Readymade.all  %>



          <div class="col-lg-2" >
            <span align="center">READYMADES</span>
                    <% @readymade.each do |grocery| %>
                        <ul class="items">
                              <div class="img-thumbnail">
                
              <%= image_tag grocery.avatar.url(:thumb) %></br>
              <span>readymades</span>
                             
              <li><span>productsid:</span><%= grocery.productid %></li>
              <li><span>productsname:</span><%= grocery.productname %></li>
              <li><span>productsdis:</span><%= grocery.productdiscription %></li>
              <%= link_to "ShopNow", welcome_readymade_path  %>
              </div>
            </ul>
            <% end %>
          </div>


           <%@electrical =Electrical.all  %>



          <div class="col-lg-2" >
            <span align="center">ELECTRICAL</span>
                    <% @electrical.each do |grocery| %>
                        <ul class="items">
                              <div class="img-thumbnail">
                
              <%= image_tag grocery.avatar.url(:thumb) %></br>
              <span>eletrical</span>
                             
              <li><span>productsid:</span><%= grocery.productid %></li>
              <li><span>productsname:</span><%= grocery.productname %></li>
              <li><span>productsdis:</span><%= grocery.productdiscription %></li>
              <%= link_to "ShopNow", welcome_electrical_path  %>
              </div>
            </ul>
            <% end %>
          </div>



            <!--  <%#= Grocery.all.collect {|s| [s.productid,s.productname,s.productdiscription,image_tag grocery.avatar.url(:thumb)]} %> -->
          
          <%#= @groceries.productname %> 

          <!-- <div class="col-lg-3">
                    <%# @grocery.each do |grocery| %>
                        <ul class="items">
                              <div class="img-thumbnail">
                
              <%#= image_tag grocery.avatar.url(:thumb) %></br>
              <span>groceries</span>
                              </div>
              <li><span>productsid:</span><%#= grocery.productid %></li>
              <li><span>productsname:</span><%#= grocery.productname %></li>
              <li><span>productsdis:</span><%#= grocery.productdiscription %></li>
            </ul>
            <%# end %>
          </div> -->
         <!--  <div class="col-lg-3">
                    <%# @product.each do |product| %>
                        <ul class="items">
                              <div class="img-thumbnail">
                
              <%#= image_tag (product.avatar.url(:thumb) )%></br>
              <span>products</span>
                              </div>
              <li><span>productsid:</span><%#= product.productid %></li>
              <li><span>productsname:</span><%#= product.productname %></li>
              <li><span>productsdis:</span><%#= product.productdiscription %></li>
            </ul>
            <%# end %>
          </div> -->
          <!-- <div class="col-lg-3">
                    <#% @product.each do |product| %>
                        <ul class="items">
                              <div class="img-thumbnail">
                
              <%#= image_tag (product.avatar.url(:thumb) )%></br>
              <span>products</span>
                              </div>
              <li><span>productsid:</span><%#= product.productid %></li>
              <li><span>productsname:</span><%#= product.productname %></li>
              <li><span>productsdis:</span><%#= product.productdiscription %></li>
            </ul>
            <%# end %>
          </div> -->








            </div>
          </div>
        </div>

app/views/welcome/productprice.html.erb
<% @product = Product.all %>

    <div class="container">
      <div class="row" style="color:blue">
        <div class="col-lg-4">
				<% @product.each do |f| %>
					<% if f.productid == 3 %>
								<%= image_tag (f.avatar.url(:thumb) )%></br>
								<% price = 300 %>

					     <span> ProductPrice :<%= price %></span>
					       <p>CashBack :10%<p>
					       		<% cost=price/100 %>
					       		<% dis=cost*10 %>
					       		<% selling =price-dis %>

					       	<span>cost:<%= selling  %>
					       		
					       		<%= link_to "AddCard", "" %>
					       	
					     <% end %>
		</div>
		<div class="col-lg-4">
					     <% if f.productid == 1002 %>
								<%= image_tag (f.avatar.url(:thumb) )%></br>
								<% price = 300 %>

					     <span> ProductPrice :<%= price %></span>
					       <p>CashBack :20%<p>
					       		<% cost=price/100 %>
					       		<% dis=cost*20 %>
					       		<% selling =price-dis %>

					       	<span>cost:<%= selling  %>
					       		<%= link_to "AddCard", "" %>
					     <% end %>







					    




	      </div>
	      <div class="col-lg-4" >
					     <% if f.productid == 1002 %>
								<%= image_tag (f.avatar.url(:thumb) )%></br>
								<% price = 300 %>

					     <span> ProductPrice :<%= price %></span>
					       <p>CashBack :20%<p>
					       		<% cost=price/100 %>
					       		<% dis=cost*40 %>
					       		<% selling =price-dis %>

					       	<span>cost:<%= selling  %>
					       		<%= link_to "AddCard", "" %>
					     <% end %>
					      <% end %>
					 </div>







	   </div>
	</div>

app/views/welcome/readymade.html.erb
<% @product = Readymade.all %>

    <div class="container">
      <div class="row" style="color:blue">
        
				<% @product.each do |f| %>
				<div class="col-lg-4">
					<% if f.productid == 1 %>
					<div class="img-thumbnail" >
								<%= image_tag (f.avatar.url(:thumb) )%></br>
								<% price = 5000 %>

					     <span> ProductPrice :<%= price %></span>
					       <p>CashBack :10%<p>
					       		<% cost=price/100 %>
					       		<% dis=cost*10 %>
					       		<% @selling =price-dis %>

					       	<span>cost:<%= @selling  %>
					       		
					       		<%= link_to "AddCard", "" %>
					</div>       	
					     <% end %>
				</div>
				<div class="col-lg-4">
					     <% if f.productid == 2 %>
					     <div class="img-thumbnail" >
								<%= image_tag (f.avatar.url(:thumb) )%></br>
								<% price = 5000 %>

					     <span> ProductPrice :<%= price %></span>
					       <p>CashBack :20%<p>
					       		<% cost=price/100 %>
					       		<% dis=cost*20 %>
					       		<% selling =price-dis %>

					       	<span>cost:<%= selling  %>
					       		<%= link_to "AddCard", "" %>
					      </div>
					     <% end %>







					    




	      		</div>
	      		<div class="col-lg-4" >
					     <% if f.productid == 3 %>
					     <div class="img-thumbnail" >
								<%= image_tag (f.avatar.url(:thumb) )%></br>
								<% price = 5000 %>

					     <span> ProductPrice :<%= price %></span>
					       <p>CashBack :40%<p>
					       		<% cost=price/100 %>
					       		<% dis=cost*40 %>
					       		<% selling =price-dis %>

					       	<span>cost:<%= selling  %>
					       		<%= link_to "AddCard", "" %>
					      </div>
					     <% end %>
					      
				</div>
				<% end %>







	   </div>
	</div>