config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  resources :allproducts
  resources :electricals
  resources :readymades
  resources :groceries
  resources :products
  devise_for :supers
  devise_for :admins
  devise_for :users
  resources :users
  get 'welcome/index'
  get 'allproduct/rice'
  get 'welcome/productprice'
  get 'welcome/groceries'
  get 'welcome/electrical'
  get 'welcome/readymade'

   root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
     
end

app/models/allproduct.rb
class Allproduct < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

def self.search(search)
	puts "search"
  if search
  	puts "ifsearch"

    where('productname LIKE ?', "%#{search}%")
    puts "tttt"
  else
    @product = Product.all
  end
end


end

app/models/electrical.rb
class Electrical < ActiveRecord::Base
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Electrical.all
  end
end



end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Grocery.all
  end
end



end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Product.all
  end
end


# def search(search)
#   if search
#     find(:all, :conditions => ['productname LIKE ?', "%#{search}%"])
#   else
#     find(:all)
#   end
# end


  
end

app/models/readymade.rb
class Readymade < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Readymade.all
  end
end




end

app/models/role.rb
class Role < ActiveRecord::Base
	has_one:user
end

app/models/super.rb
class Super < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        belongs_to :role
      

end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  before_action :set_grocery, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @groceries = Grocery.all
    respond_with(@groceries)
  end

  def show
    respond_with(@grocery)
  end

  def new
    @grocery = Grocery.new
    respond_with(@grocery)
  end

  def edit
  end

  def create
    @grocery = Grocery.new(grocery_params)
    @grocery.save
    respond_with(@grocery)
  end

  def update
    @grocery.update(grocery_params)
    respond_with(@grocery)
  end

  def destroy
    @grocery.destroy
    respond_with(@grocery)
  end

  private
    def set_grocery
      @grocery = Grocery.find(params[:id])
    end

    def grocery_params
      params.require(:grocery).permit(:productid, :productname, :productdiscription, :avatar)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    puts "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
  	@product = Allproduct.search(params[:search])
    puts "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"
  	#@product = Electrical.search(params[:search])
  	#@product = Grocery.search(params[:search])
  	#@product = Readymade.search(params[:search])
  	
  end
  def productprice
  end
  def groceries
  end
end

app/helpers/allproduct_helper.rb
module AllproductHelper
end

app/helpers/allproducts_helper.rb
module AllproductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/electricals_helper.rb
module ElectricalsHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/readymades_helper.rb
module ReadymadesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groceries/_form.html.erb
<%= simple_form_for(@grocery) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :productid %>
    <%= f.input :productname %>
    <%= f.input :productdiscription %>
    <%= f.input :avatar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groceries/edit.html.erb
<h1>Editing Grocery</h1>

<%= render 'form' %>

<%= link_to 'Show', @grocery %> |
<%= link_to 'Back', groceries_path %>

app/views/groceries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groceries</h1>

<table>
  <thead>
    <tr>
      <th>Productid</th>
      <th>Productname</th>
      <th>Productdiscription</th>
      <th>Productimage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groceries.each do |grocery| %>
      <tr>
        <td><%= grocery.productid %></td>
        <td><%= grocery.productname %></td>
        <td><%= grocery.productdiscription %></td>
        <td><%= image_tag grocery.avatar.url(:thumb) %></td>?
        <td><%= link_to 'Show', grocery %></td>
        <td><%= link_to 'Edit', edit_grocery_path(grocery) %></td>
        <td><%= link_to 'Destroy', grocery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grocery', new_grocery_path %>

app/views/groceries/new.html.erb
<h1>New Grocery</h1>

<%= render 'form' %>

<%= link_to 'Back', groceries_path %>

app/views/groceries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productid:</strong>
  <%= @grocery.productid %>
</p>

<p>
  <strong>Productname:</strong>
  <%= @grocery.productname %>
</p>

<p>
  <strong>Productdiscription:</strong>
  <%= @grocery.productdiscription %>
</p>
<p><%= image_tag @grocery.avatar.url(:thumb) %></p>

<%= link_to 'Edit', edit_grocery_path(@grocery) %> |
<%= link_to 'Back', groceries_path %>