config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  resources :allproducts
  resources :electricals
  resources :readymades
  resources :groceries
  resources :products
  devise_for :supers
  devise_for :admins
  devise_for :users
  resources :users
  get 'welcome/index'
  get 'allproduct/rice'
  get 'welcome/productprice'
  get 'welcome/groceries'
  get 'welcome/electrical'
  get 'welcome/readymade'

   root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
     
end

app/models/allproduct.rb
class Allproduct < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

def self.search(search)
	puts "search"
  if search
  	puts "ifsearch"

    where('productname LIKE ?', "%#{search}%")
    puts "tttt"
  else
    @product = Product.all
  end
end


end

app/models/electrical.rb
class Electrical < ActiveRecord::Base
	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Electrical.all
  end
end



end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Grocery.all
  end
end



end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Product.all
  end
end


# def search(search)
#   if search
#     find(:all, :conditions => ['productname LIKE ?', "%#{search}%"])
#   else
#     find(:all)
#   end
# end


  
end

app/models/readymade.rb
class Readymade < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  if search
    where('productname LIKE ?', "%#{search}%")
  else
    @product = Readymade.all
  end
end




end

app/models/role.rb
class Role < ActiveRecord::Base
	has_one:user
end

app/models/super.rb
class Super < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        belongs_to :role
      

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/allproduct_helper.rb
module AllproductHelper
end

app/helpers/allproducts_helper.rb
module AllproductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/electricals_helper.rb
module ElectricalsHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/readymades_helper.rb
module ReadymadesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_logged_nav.html.erb
   <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Ecommerce", root_path, :class=>"navbar-brand"%>
                
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <%= current_user.email %>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><%= link_to "products", welcome_index_path %></li>
                        <li><%= link_to "Create Products", new_product_path %></li>
                        <li><%= link_to "Create groceries", new_grocery_path %></li>
                        <li><%= link_to "Create readymade", new_readymade_path %></li>
                        <li><%= link_to "Create eletrical", new_electrical_path %></li>



                <li class="divider"></li>
                        <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
               
               
            </ul>
            <!-- /.navbar-top-links -->

           
        </nav>

     <!--  <div id="light" class="white_content"> <a href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'"><div class ="move">Close</div></a>
  <%#= form_for(User.new,:remote => true, :url => registration_path(User.new)) do |f| %>
<%#= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%#= devise_error_messages! %>

  <h4>Generate email and password </h4>
  <div class="field">
    <%#= f.label :email %><br />
    <%#= f.email_field :email, autofocus: true,:class=>'form-control' %>
      </div>

  <div class="field">
    <%#= f.label :password %>
    
    <%#= f.password_field :password,:class=>'form-control'%>
  </div>
   <div class="actions">
    <a href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'">
    <%#= f.submit "Create" %></a>
  </div>
<%# end %>
</div>

    </div>
    <!-- /#wrapper -->
 

app/views/layouts/_loggednon.html.erb
<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Ecommerce", root_path, :class=>"navbar-brand"%>
                
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <%= current_user.email %>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><%= link_to "Profile", edit_user_registration_path %></li>
                        <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
               
               
            </ul>
            <!-- /.navbar-top-links -->

           
        </nav>

        
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

app/views/layouts/_navbar.html.erb
<style>
.navbar-default .navbar-brand {
color: #777777;
padding-top: 15px;
}
</style>

<div id="wrapper">
         
       <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <div class="ecomm" style = "top: 25px;">
      <%= link_to "Ecommerce", root_path, :class=>"navbar-brand"%>
    </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "ALLPRODUCTS", welcome_index_path  %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <%= form_tag allproducts_path, :method => 'get', :id => "products_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <% end %>
      </form>
      <ul class="nav navbar-nav navbar-left">

             <li class="dropdown">
                            <ul class="nav pull-right">
                                    <li class="dropdown" id="menuLogin" style = "top: 130%;">
                                             <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="navLogin" style = "top: 5px;">Login</a>
                                                    <div class="dropdown-menu" style="padding: 34px;margin-top: 18px;">
    <%= simple_form_for(User.new, url: session_path(User.new)) do |f| %>
    <div class="form-inputs">
    <%= f.input :email, required: false, autofocus: true %>
    <%= f.input :password, required: false %>
    <%#= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
    </div>

    <div class="form-actions">
    <%= f.button :submit, "Sign in" %>
    </div>
    <% end %>



                     </li>

              <%#= link_to "LOGIN", new_user_session_path %></ul>
                    
                </li>
              </ul>
               












<ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">youraccount<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">add</a></li>
            <li><a href="#">add</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
          
        </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">yourcard<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">add</a></li>
                      <li><a href="#">add</a></li>
                      <li><a href="#">Something else here</a></li>
                      <li class="divider"></li>
                      <li><a href="#">Separated link</a></li>
                    </ul>
                    
                  </li>

                   
                      

























      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
        
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

app/views/layouts/_super.html.erb
   <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <%= link_to "Ecommerce", root_path, :class=>"navbar-brand"%>
                
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <%= current_user.email %>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><%#= link_to "products", products_path %></li>
                        <li><%= link_to "Create Admin", new_admin_registration_path %></li>

                <li class="divider"></li>
                        <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
               
               
            </ul>
            <!-- /.navbar-top-links -->

           
        </nav>

     <!--  <div id="light" class="white_content"> <a href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'"><div class ="move">Close</div></a>
  <%#= form_for(User.new,:remote => true, :url => registration_path(User.new)) do |f| %>
<%#= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%#= devise_error_messages! %>

  <h4>Generate email and password </h4>
  <div class="field">
    <%#= f.label :email %><br />
    <%#= f.email_field :email, autofocus: true,:class=>'form-control' %>
      </div>

  <div class="field">
    <%#= f.label :password %>
    
    <%#= f.password_field :password,:class=>'form-control'%>
  </div>
   <div class="actions">
    <a href = "javascript:void(0)" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'">
    <%#= f.submit "Create" %></a>
  </div>
<%# end %>
</div>

    </div>
    <!-- /#wrapper -->
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RailsTech" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  
  <body class="rowmainbg">

    <% if user_signed_in? %>
   <% if current_user.email == "admin@example.com"%>
    <%# if current_user.role?(:admin) %>
  <%= render :partial => 'layouts/logged_nav' %>
  <% elsif  current_user.email == "super@example.com" %>
  <%= render :partial => 'layouts/super' %>
          
  <% else%>
  <%= render :partial => 'layouts/loggednon' %>

  <% end %>


  <% else %>
  <%= render :partial => 'layouts/navbar' %>
  <% end %>

    <div class = "app" style = "padding-top: 0px;">
          <%#= bootstrap_flash %>
          <%= yield %>
         </div>
        
      

                    
                     

                   
     <div class="l-subfooter at_bottom">
      <div class="l-subfooter-h i-cf">

          <div class="w-copyright">© 2015 Ecommercer LAXMIMAYEETECHNOLOGIES. All Rights Reserved</div>
        </div>
      </div>


  </body>
</html>